### ISSUE TITLE
Regarding the installation of w2dynamics.

### ISSUE THREAD

**Issue by sujanbharadwaj** [w2dynamics/w2dynamics#18]
Dear w2dynamics developers,
I am trying to install w2dynamics (in Ubuntu). I have done all the prerequisite installations. And I have followed the steps mentioned in the GitHub.
When I run **make test**, It runs fine, as shown in the below screenshot. 
![Screenshot from 2022-11-11 22-35-47](https://user-images.githubusercontent.com/45603592/201393678-97cd16df-5deb-44e5-b0fd-c7b84c76a193.png)
Also, **make**, **make CTQMC**, and **make install** runs without any errors. But when I run **DMFT.py**, it throws an error saying _ImportError: No module named CTQMC_. Please find the below screenshot of the error. Please help me out.
![Screenshot from 2022-11-11 22-36-15](https://user-images.githubusercontent.com/45603592/201393684-046da1ab-805d-404a-aba9-e6778e544ab4.png)
Thanks
Sujan K K

**Comment by alexkowalski** [comment]
Dear Sujan K K,

assuming that the entire content of the `w2dyn` directory after successfully running `make CTQMC` was copied to the location indicated in your screenshots, your problem may just be that the CMake script is written to preferentially use a version of Python > 3.0 for building, while the executable scripts specify `python` as interpreter, which may be a version of Python < 3.0. If that is the case, you should be able to run the programs by explicitly specifying the correct version of the python interpreter executable using a command like `python3 /usr/local/bin/DMFT.py` or by changing the first line of the installed scripts such that the correct interpreter is specified.

If that does not solve your problem, please check that a file with a name of the form `CTQMC[.*].so` is present in the installation directory under `w2dyn/auxiliaries`, or, if that is not the case, in the source directory. If you find such a file somewhere, make sure that it is present under `w2dyn/auxiliaries` in the directory that should be used for loading the modules from. If `make` and `make install` run correctly, this should actually already be the case, but at first glance the directory of your installed copy of `w2dyn` does not seem like one that `make install` is actually supposed to copy it to. If you do not find any such file, your `make` step did probably not succeed. If you need further help for that reason or any other reason, please try to find out what exactly went wrong or provide terminal output of all the steps you performed after obtaining the source code, i.e. in particular presumably `cmake`, `make`, and  `make install`.

Best regards,
Alexander Kowalski

**Comment by sujanbharadwaj** [comment]
Thank you, it is working now.
