### ISSUE TITLE
w2dynamics incompatible with numpy > 1.24

### ISSUE THREAD

**Issue by deecadance** [w2dynamics/w2dynamics#19]
See [numpy 1.24 release notes](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations):
> The deprecation for the aliases np.object, np.bool, np.float, np.complex, np.str, and np.int is expired (introduces NumPy 1.20). Some of these will now give a FutureWarning in addition to raising an error since they will be mapped to the NumPy scalars in the future.

In short, all instances of np.float and np.complex now raise errors instead of warnings, which exits the code. Replacing them with their python version (float, complex) seems to have fixed the problem for me.

**Comment by alexkowalski** [comment]
Yes, you are right, sorry about the delay. I have just applied the fix, there should be no more problems in this regard.
